categories = {
    "emotions" : ["aback", "abandoned", "abashed", "afraid", "agreeable", "amused", "amusing", "angry", "annoyed", "annoying", "anxious", "apathetic", "ashamed", "astonishing", "aware", "bashful", "bewildered", "bored", "boring", "brave", "cagey", "calm", "caring", "cheerful", "concerned", "confused", "courageous", "crabby", "craven", "crazy", "creepy", "curious", "cynical", "dazzling", "delighted", "delirious", "depressed", "desperate", "disappointed", "disgusted", "disturbed", "eager", "embarrassed", "encouraged", "enthusiastic", "envious", "excited", "exciting", "fearful", "fearless", "feel", "fretful", "friendly", "frightened", "furious", "glad", "gloomy", "goofy", "grateful", "grouchy", "happy", "hateful", "helpful", "helpless", "hesitant", "hopeful", "horrible", "hurt", "hysterical", "ignorant", "impressed", "insecure", "interested", "irritating", "jealous", "jittery", "jolly", "joyous", "judgmental", "kind", "lonely", "lovable", "loving", "mad", "mean", "melancholy", "miserable", "nervous", "nice", "nostalgic", "offended", "optimistic", "peaceful", "pleased", "proud", "relieved", "resentful", "sad", "satisfied", "scared", "serious", "shy", "silly", "sympathetic", "tense", "terrified", "thankful", "tired", "uncomfortable", "upset", "worried", "wounded"],

    "physical" : ["abnormal", "able", "adaptable", "agile", "alert", "athletic", "awkward", "balanced", "big", "billowy", "black", "blue", "blue-eyed", "blushing", "bony", "bouncy", "brawny", "breakable", "bright", "broad", "broken", "brown", "bumpy", "burly", "bushy", "chunky", "clumsy", "compact", "crooked", "curved", "curvy", "delicate", "elastic", "elfin", "faint", "fair", "fat", "feeble", "fertile", "few", "fine", "flimsy", "flexible", "floppy", "fluffy", "fragile", "frail", "fuzzy", "giant", "gifted", "glamorous", "graceful", "gray", "green", "hard", "heavy", "high", "huge", "hulking", "lean", "light", "limber", "limping", "little", "long", "loose", "low", "lumpy", "massive", "meager", "muscular", "narrow", "nimble", "petite", "powerful", "puffy", "puny", "round", "sharp", "short", "silky", "skinny", "sleek", "slender", "slimy", "sloppy", "slim", "smooth", "square", "stiff", "straight", "sturdy", "substantial", "tall", "thick", "thin", "tiny", "uneven", "weighty", "wide", "wiry"],

    "color" : ["black", "black-and-white", "blue", "blue-eyed", "brown", "green", "grey", "magenta", "orange", "pink", "purple", "red", "white", "yellow"],

    "personality" : ["able", "adaptable", "adventurous", "aggressive", "agreeable", "aloof", "ambitious", "arrogant", "assertive", "bashful", "belligerent", "bold", "calculating", "callous", "calm", "capricious", "careful", "careless", "charitable", "charming", "chivalrous", "clever", "compassionate", "cooperative", "courageous", "cowardly", "creative", "cruel", "curious", "cynical", "daring", "decisive", "defiant", "dependable", "determined", "didactic", "diligent", "diplomatic", "disciplined", "dramatic", "dreamy", "dynamic", "eager", "earnest", "easy-going", "eccentric", "educated", "efficient", "egotistical", "elaborate", "elegant", "emotional", "empathetic", "enthusiastic", "ethical", "exuberant", "fair", "faithful", "fantastic", "fearless", "flexible", "frank", "friendly", "frugal", "generous", "gentle", "gifted", "goofy", "gracious", "grandiose", "greedy", "grouchy", "helpful", "honest", "honorable", "humble", "idealistic", "imaginative", "impartial", "independent", "industrious", "ingenious", "innovative", "inquisitive", "insightful", "intelligent", "interesting", "intuitive", "inventive", "judgmental", "kind", "kindhearted", "knowledgeable", "lazy", "logical", "loyal", "malicious", "mature", "mean", "methodical", "modest", "mysterious", "naïve", "narrow-minded", "natural", "noble", "nosy", "objective", "observant", "obsessive", "open-minded", "optimistic", "original", "outgoing", "passionate", "patient", "perceptive", "persistent", "philosophical", "playful", "polite", "practical", "precise", "prejudiced", "presentable", "principled", "proactive", "professional", "progressive", "punctual", "rational", "realistic", "reasonable", "rebellious", "reckless", "reflective", "reliable", "resourceful", "respectful", "responsible", "responsive", "rigid", "robust", "romantic", "rough", "rude", "ruthless", "sarcastic", "scholarly", "self-centered", "sensitive", "serious", "shameless", "sharp", "skeptical", "skilled", "sociable", "sophisticated", "spontaneous", "stern", "strategic", "stubborn", "supportive", "sympathetic", "systematic", "talented", "tactful", "tenacious", "thoughtful", "thrifty", "tolerant", "tough", "traditional", "tricky", "trustworthy", "unpredictable", "unselfish", "versatile", "virtuous", "visionary", "warm", "whimsical", "wise", "witty", "zealous"],

    "age" : ["ancient", "early", "elderly", "juvenile", "new", "old", "old-fashioned", "prime", "young", "youthful"],

    "size" : ["big", "enormous", "extra-large", "extra-small", "giant", "huge", "little", "miniature", "small", "teeny", "teeny-tiny", "tiny"],

    "senses" : ["acidic", "acoustic", "aromatic", "bitter", "boiling", "bright", "damp", "dark", "deafening", "deep", "heavy", "light", "loud", "melodic", "mild", "noisy", "noiseless", "quiet", "rough", "sharp", "shiny", "smooth", "soft", "sour", "spicy", "sweet", "tight", "warm"],

    "mental state" : ["absent", "absent-minded", "acute", "alert", "analytical", "anxious", "aware", "bewildered", "brilliant", "clever", "complex", "confused", "conscious", "curious", "dazed", "deep", "delirious", "dependent", "determined", "distracted", "dizzy", "educated", "experimental", "focused", "forgetful", "imaginative", "incandescent", "inquisitive", "intelligent", "interested", "introspective", "irrational", "knowing", "knowledgeable", "learned", "logical", "mindless", "naive", "observant", "philosophical", "puzzled", "rational", "reasonable", "reflective", "scholarly", "thoughtful", "uncertain", "unconscious", "understood", "uninterested", "wise"],

    "condition" : ["abundant", "accurate", "adequate", "alive", "average", "bad", "best", "better", "blank", "clean", "complete", "defective", "dirty", "dry", "dull", "empty", "excellent", "flawless", "fresh", "functional", "good", "great", "imperfect", "incomplete", "inferior", "intact", "neat", "normal", "obsolete", "perfect", "poor", "pure", "rotten", "spotless", "stale", "straight", "substantial", "superior", "terrible", "twisted", "unique", "used", "useless", "whole", "worse", "wrong"],

    "intensity" : ["absolute", "acute", "advanced", "colossal", "complete", "compelling", "deep", "dramatic", "enormous", "extreme", "full", "great", "high", "immense", "intense", "keen", "major", "maximum", "mild", "minimum", "momentous", "obvious", "overwhelming", "powerful", "prime", "profound", "serious", "severe", "strong", "substantial", "supreme", "terrible", "tremendous", "ultimate", "vast"],

    "motion" : ["active", "agile", "animated", "bustling", "busy", "changing", "dynamic", "energetic", "fast", "fluid", "frantic", "free", "frantically", "quick", "restless", "spinning", "static", "swift", "walking", "wiggly"],

    "time" : ["current", "eternal", "future", "immediate", "long", "momentary", "modern", "new", "periodic", "perpetual", "present", "previous", "recent", "temporary", "timeless", "transient", "ultimate"],

    "context" : ["abstract", "accessible", "actual", "appropriate", "artificial", "authentic", "awkward", "basic", "certain", "commercial", "competitive", "contrary", "convenient", "creative", "critical", "crucial", "current", "customary", "different", "direct", "equal", "essential", "exact", "exclusive", "exotic", "familiar", "general", "genuine", "global", "ideal", "identical", "implicit", "impossible", "individual", "internal", "legal", "local", "logical", "main", "material", "natural", "necessary", "neutral", "normal", "objective", "obvious", "official", "opposite", "organic", "particular", "passive", "potential", "practical", "precious", "primary", "private", "probable", "professional", "public", "random", "rational", "real", "relative", "relevant", "reliable", "remarkable", "representative", "respective", "right", "rigid", "sacred", "secondary", "secret", "similar", "social", "specific", "standard", "technical", "typical", "unique", "universal", "valuable", "various", "virtual", "widespread"],
}